version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      # creating a database when container is initialised
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./mongodb-data:/data/db
  subscribeapi:
    image: subscribeapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/test
      API_PORT: 3000
    ports:
      - 3000:3000
